# Generated by Django 5.2.17 on 2026-09-18 15:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_placeimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Длинное описание"),
        ),
    ]
