# Generated by Django 5.2.17 on 2026-09-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_alter_place_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Широта"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="lng",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Долгота"
            ),
        ),
    ]
